postgresql:
  enabled: false

ingress:
  hostname: posthog.example.com

posthog:
  optOutCapture: true

externalPostgresql:
  host: posthog-pg-postgresql
  port: 5432
  database: posthog
  personsDatabase: posthog
  cyclotronDatabase: cyclotron
  secretName: posthog-pg-postgresql-account-postgres
  usernameKey: username
  passwordKey: password
