{{- if .Values.metrics.enabled }}
## Web ServiceMonitor
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "posthog.fullname" . }}-web
  labels:
    {{- include "posthog.componentLabels" (dict "root" . "component" "web") | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "posthog.componentSelectorLabels" (dict "root" . "component" "web") | nindent 6 }}
  endpoints:
    - port: http
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
      path: /_health
## Plugins ServiceMonitor
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "posthog.fullname" . }}-plugins
  labels:
    {{- include "posthog.componentLabels" (dict "root" . "component" "plugins") | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "posthog.componentSelectorLabels" (dict "root" . "component" "plugins") | nindent 6 }}
  endpoints:
    - port: http
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
      path: /_health
## Capture ServiceMonitor
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "posthog.fullname" . }}-capture
  labels:
    {{- include "posthog.componentLabels" (dict "root" . "component" "capture") | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "posthog.componentSelectorLabels" (dict "root" . "component" "capture") | nindent 6 }}
  endpoints:
    - port: http
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
      path: /_readiness
{{- end }}
