apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: posthog-clickhouse-password
  namespace: posthog
spec:
  secretTemplate:
    type: Opaque
    stringData:
      password: $(value)
