apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - clickhouse-admin-secret.example.yaml
  - clickhouse-config.yaml
  - clickhouse.yaml
  - clickhouse-service.yaml
  - postgres-kubeblocks.yaml
