apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - issuer.yaml
  - oidc-certificate.yaml
  - postgres-cnpg.yaml
  - clickhouse-password.yaml
  - altinity-clickhouse-operator.yaml
  - clickhouse-keeper.yaml
  - clickhouse-initdb.yaml
  - clickhouse.yaml
  - redpanda-operator.yaml
  - redpanda.yaml
  - ocirepository.yaml
  - release.yaml
