apiVersion: v1
kind: Secret
metadata:
  name: posthog-oidc
  namespace: posthog
type: Opaque
stringData:
  oidc-rsa-private-key: |
    -----BEGIN PRIVATE KEY-----
    REPLACE_WITH_YOUR_OWN_OIDC_RSA_PRIVATE_KEY
    -----END PRIVATE KEY-----
