apiVersion: apps.kubeblocks.io/v1
kind: Cluster
metadata:
  name: posthog-pg
  namespace: posthog
spec:
  terminationPolicy: WipeOut
  clusterDef: postgresql
  topology: replication
  componentSpecs:
    - name: postgresql
      serviceVersion: "16.9.0"
      disableExporter: false
      replicas: 2
      resources:
        requests:
          cpu: "500m"
          memory: 1Gi
        limits:
          cpu: "2"
          memory: 4Gi
      volumeClaimTemplates:
        - name: data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
