apiVersion: v1
kind: Secret
metadata:
  name: posthog-pg-app
  namespace: posthog
type: Opaque
stringData:
  username: postgres
  password: change-me
  uri: postgres://postgres:change-me@posthog-pg-postgresql:5432/posthog
  persons-uri: postgres://postgres:change-me@posthog-pg-postgresql:5432/posthog
  cyclotron-uri: postgres://postgres:change-me@posthog-pg-postgresql:5432/cyclotron
