apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: elastic
  namespace: elastic-system
spec:
  url: https://helm.elastic.co
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: eck-operator
  namespace: elastic-system
spec:
  interval: 1h
  chart:
    spec:
      chart: eck-operator
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: elastic-system
      version: "3.5.0"
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
