{
  "apiVersion": "traefik.io/v1alpha1",
  "kind": "Middleware",
  "spec": {
    "headers": {
      "customResponseHeaders": {
        "Cache-Control": "public, max-age=31536000, immutable"
      }
    }
  },
  "metadata": {
    "name": "posthog-static-cache",
    "namespace": "posthog"
  }
}
